name: Set Global Environment Variables

on:
  workflow_call:
    outputs:
      package_name:
        value: 'wavefront_sdk'
      requirements:
        value: 'Deprecated requests tdigest'

jobs:
  envset:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This job sets environment variables for others."
